config/routes.rb
Rails.application.routes.draw do

  resources :players do
    collection do
      get :NA
      get :EU
      get :SA
      get :AS
      get :OC
    end
  end

  root 'players#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  validates :nick, presence: true, length: { maximum: 20 }
  validates :description, length: { maximum: 275 }
  validates :server, presence: true, length: { maximum: 2 }#, if: :server_exists?
  VALID_URL_REGEX = /\Ahttps?:\/\/(www\.)?steamcommunity.com.*\z/i
  validates :steam_link, presence: true, length: { maximum: 255 },
                         format: { with: VALID_URL_REGEX },
                         uniqueness: { case_sensitive: false }

  scope :NA, -> { where(server: 'NA')}
  scope :EU, -> { where(server: 'EU')}
  scope :SA, -> { where(server: 'SA')}
  scope :AS, -> { where(server: 'AS')}
  scope :OC, -> { where(server: 'OC')}

  def server_exists?
    ['NA', 'SA', 'EU', 'AS', 'OC'].include? self[:server]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all.page(params[:page]).per_page(12).order(created_at: :desc)
    @server = 'all'
  end

  def NA
    @players = Player.NA.all.page(params[:page]).per_page(12).order(created_at: :desc)
    @server = 'NA'
    render action: :index
  end

  def EU
    @players = Player.EU.all.page(params[:page]).per_page(12).order(created_at: :desc)
    @server = 'EU'
    render action: :index
  end

  def SA
    @players = Player.SA.all.page(params[:page]).per_page(12).order(created_at: :desc)
    @server = 'SA'
    render action: :index
  end

  def AS
    @players = Player.AS.all.page(params[:page]).per_page(12).order(created_at: :desc)
    @server = 'AS'
    render action: :index
  end

  def OC
    @players = Player.OC.all.page(params[:page]).per_page(12).order(created_at: :desc)
    @server = 'OC'
    render action: :index
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to action: "index" and flash[:success] = 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
=begin
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end
=end

  # DELETE /players/1
  # DELETE /players/1.json
=begin
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
=end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:steam_link, :nick, :description, :server)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Where Is My Squad</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/ec1f88470f.js"></script>
    <!-- jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Where is my Squad?<sup> beta</sup></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <!--<ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                        </li>
                </ul>-->
                <ul class="nav navbar-nav navbar-right">
                  <li>
                    <p class="navbar-text">Let's keep this server running! </p>
                  </li>
                  <li>
                    <p>
                      <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="AXRPAMC3DVLRE">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/pt_BR/i/scr/pixel.gif" width="1" height="1">
                      </form>
                    </p>
                  </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "flash alert-#{key}" %>
      <% end %>
    </div>


    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :steam_link %>
    <%= form.text_field :steam_link, id: :player_steam_link %>
  </div>

  <div class="field">
    <%= form.label :nick %>
    <%= form.text_field :nick, id: :player_nick %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :player_description %>
  </div>

  <div class="field">
    <%= form.label :server %>
    <%= form.text_field :server, id: :player_server %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/_player.html.erb
<% @players.each_slice(3) do |players| %>
<div class="row">
    <% players.each do |player| %>
    <div class="col-sm-4 portfolio-item">
        <!--<a href="#">
            <img class="img-responsive" src="http://placehold.it/700x400" alt="">
        </a>-->
        <h3>
            <a target="_blank" href=<%= player.steam_link %>><%= player.nick %></a>
        </h3>
        <p><b>Server: </b><%= player.server %></p>
        <p class="line"><%= player.description %></p>
    </div>
    <% end %>
</div>
<% end %>

app/views/players/index.html.erb
<!-- Page Content -->
<div class="container">
    <% if @server == 'all'%>
      <div class="row">
        <div class="col-md-12">
          <div class = "alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden = "true">
            &times;
            </button>
           <strong>Where is my Squad?</strong> is a website where you can find other PUBG players who want to play with teammates!<br>
           <br><strong>How to use?</strong><br>
           <strong>1)</strong> Add yourself as a player.<br>
           <strong>2)</strong> Choose your server and look for players who added themselves.<br>
                   That's it!<br><br>

            Your entry will be <strong>deleted after 6 hours</strong>, so if you want to find more players later, just repeat the process!
          </div>
        </div>
      </div>
    <% end %>
    <!-- Page Header -->
    <div class="row">
        <div class="col-md-12">
            <h1 class="page-header">Players
              <small>
                <% if @server == 'all'%>
                  <b>
                <% end %>
                <a href="/players">All Servers</a>
                <% if @server == 'all'%>
                  </b>
                <% end %>
              </small>
                <small> | </small>
                <small>
                  <% if @server == 'NA'%>
                    <b>
                  <% end %>
                  <a href="/players/NA">NA</a>
                  <% if @server == 'NA'%>
                    </b>
                  <% end %>
                </small>
                <small> | </small>
                <small>
                  <% if @server == 'EU'%>
                    <b>
                  <% end %>
                  <a href="/players/EU">EU</a>
                  <% if @server == 'EU'%>
                    </b>
                  <% end %>
                </small>
                <small> | </small>
                <small>
                  <% if @server == 'SA'%>
                    <b>
                  <% end %>
                  <a href="/players/SA">SA</a>
                  <% if @server == 'SA'%>
                    </b>
                  <% end %>
                </small>
                <small> | </small>
                <small>
                  <% if @server == 'AS'%>
                    <b>
                  <% end %>
                  <a href="/players/AS">AS</a>
                  <% if @server == 'AS'%>
                    </b>
                  <% end %>
                </small>
                <small> | </small>
                <small>
                  <% if @server == 'OC'%>
                    <b>
                  <% end %>
                  <a href="/players/OC">OC</a>
                  <% if @server == 'OC'%>
                    </b>
                  <% end %>
                </small>
                <small class="pull-right">
                  <a class="btn btn-success"
                  href="/players/new" role="button">Add yourself as a player!</a>
                </small>
            </h1>
        </div>
    </div>
    <!-- /.row -->

    <!-- Projects Row -->
    <% @players.each_slice(3) do |players| %>
    <div class="row">
        <% players.each do |player| %>
        <div class="col-sm-4 portfolio-item">
            <!--<a href="#">
                <img class="img-responsive" src="http://placehold.it/700x400" alt="">
            </a>-->
            <h3>
                <a target="_blank" href=<%= player.steam_link %>><%= player.nick %></a>
            </h3>
            <p><b>Server: </b><%= player.server %></p>
            <p class="line"><%= player.description %></p>
        </div>
        <% end %>
    </div>
    <% end %>
    <!-- /.row -->

    <hr>

    <!-- Pagination -->
    <div class="row text-center">
        <div class="col-lg-12">
            <%= will_paginate @players, renderer: BootstrapPagination::Rails %>
        </div>
    </div>
    <!-- /.row -->

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-6">
                <p>Copyleft | Where is my Squad?</p>
            </div>
            <div class="col-lg-6">
              <p align="right">This website is 
                <a href="https://github.com/matheus-manoel/Where-is-My-Squad-"> open source! </a>
                <i class="fa fa-github fa-2x" aria-hidden="true"></i></p>
            </div>
        </div>
        <!-- /.row -->
    </footer>

</div>

app/views/players/index.js.erb
$('#players').append('<%= j render(@players) %>');
<% if @players.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@players) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>

app/views/players/new.html.erb
<%= provide(:title, 'Add Player') %>

<h1 align="center">Add Player</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@player) do |f| %>
      <div id="error_explanation">
        <% if @player.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

            <ul>
            <% @player.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      </div>

        <%= f.label :steam_link %>
        <%= f.text_field :steam_link, class: "form-control" %>

        <%= f.label :nick %>
        <%= f.text_field :nick, class: "form-control" %>

        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>

        <%= f.label :server %>
        <%= f.select :server, [["NA", "NA"],
                              ["EU", "EU"],
                              ["SA", "SA"],
                              ["OC", "OC"],
                              ["AS", "AS"]], { class: "selectpicker" } %>

        <br>

        <div align="center">
          <%= f.submit "Add", class:"btn btn-success" %>
        </div>

      <% end %>
    </div>
</div>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Steam link:</strong>
  <%= @player.steam_link %>
</p>

<p>
  <strong>Nick:</strong>
  <%= @player.nick %>
</p>

<p>
  <strong>Description:</strong>
  <%= @player.description %>
</p>

<p>
  <strong>Server:</strong>
  <%= @player.server %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>